# Generated by Django 4.2.6 on 2023-10-09 20:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0006_complaint_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="owner_pure_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="active",
            field=models.BooleanField(
                db_index=True, null=True, verbose_name="Активно-ли объявление"
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="has_balcony",
            field=models.BooleanField(
                db_index=True, null=True, verbose_name="Наличие балкона"
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
