# Generated by Django 4.2.6 on 2023-10-09 20:47

from django.db import migrations
import phonenumbers


def change_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for number in Flat.objects.all():
        current_number = number.owners_phonenumber
        if phonenumbers.is_valid_number(phonenumbers.parse(current_number, 'RU')):
            correct_number = phonenumbers.parse(current_number, 'RU')
            new_number = correct_number.national_number
            number.owner_pure_phone = f'+7{new_number}'
            number.save()


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0008_alter_flat_active"),
    ]

    operations = [
        migrations.RunPython(change_phone_number)
    ]



