# Generated by Django 4.2.6 on 2023-10-09 20:47

from django.db import migrations
import phonenumbers


def change_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all().iterator():
        current_number = flat.owners_phonenumber
        if phonenumbers.is_valid_number(phonenumbers.parse(current_number, 'RU')):
            correct_number = phonenumbers.parse(current_number, 'RU')
            new_number = phonenumbers.format_number(correct_number, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
            flat.owner_pure_phone = new_number
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0008_alter_flat_active"),
    ]

    operations = [
        migrations.RunPython(change_phone_number)
    ]

