# Generated by Django 4.2.6 on 2023-10-10 06:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0009_auto_20231009_2347"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flat",
            name="owner_pure_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region=None,
                verbose_name="Нормализованный номер владельца",
            ),
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=128, verbose_name="ФИО владельца"),
                ),
                (
                    "phone_number_owner",
                    models.CharField(max_length=128, verbose_name="Номер владельца"),
                ),
                (
                    "owner_pure_phone_number",
                    models.CharField(
                        max_length=128, verbose_name="Нормализованный номер владельца"
                    ),
                ),
                (
                    "flat_in_owner",
                    models.ManyToManyField(
                        related_name="flats_in_owner",
                        to="property.flat",
                        verbose_name="Квартиры в собственности",
                    ),
                ),
            ],
        ),
    ]
