# Generated by Django 4.2.6 on 2023-10-10 06:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0010_alter_flat_owner_pure_phone_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="owner_pure_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region=None,
                verbose_name="Нормализованный номер владельца",
            ),
        ),
    ]
