# Generated by Django 4.2.6 on 2023-10-11 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0012_auto_20231010_1039"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flat",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="flat",
            name="owner_pure_phone",
        ),
        migrations.RemoveField(
            model_name="flat",
            name="owners_phonenumber",
        ),
        migrations.AddField(
            model_name="flat",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_flats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто лайкнул:",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="number_flat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to="property.flat",
                verbose_name="Квартира, на которую жалуются:",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_who_complained",
                to=settings.AUTH_USER_MODEL,
                unique=True,
                verbose_name="Кто жаловался:",
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="has_balcony",
            field=models.BooleanField(
                db_index=True, default=1, verbose_name="Наличие балкона"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flat",
            name="new_building",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Является ли объект новостройкой"
            ),
        ),
    ]
