# Generated by Django 4.2.6 on 2023-10-18 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0015_rename_number_flat_complaint_flat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="owner",
            old_name="phone_number_owner",
            new_name="number",
        ),
        migrations.AlterField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to=settings.AUTH_USER_MODEL,
                unique=True,
                verbose_name="Кто жаловался:",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="flats",
            field=models.ManyToManyField(
                related_name="owners",
                to="property.flat",
                verbose_name="Квартиры в собственности",
            ),
        ),
    ]
